# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cedb462ae983580bb873431ec9b6eb7321f51ac63cea75f886cde7911616b51a9c8c18c6f4eb178301eee81586ba266622d94e8517ff837543a2b2e5d8601be4

test:
  secret_key_base: 64871cb2b60ef01c19d321e1a708283fc4b33856b9e678fa8a934b7ef6220209f169e1122d2019f3a733ba0a22e040cb6561869ef30b3cd4c75b07355bbe55ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
